# Generated by Django 4.1.4 on 2022-12-20 05:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_sighting'),
    ]

    operations = [
        migrations.AddField(
            model_name='sighting',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 12, 20, 5, 21, 31, 556814)),
        ),
    ]
