# Generated by Django 4.1.4 on 2022-12-20 05:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_sighting_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sighting',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
