# Generated by Django 4.1.4 on 2022-12-20 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_sighting_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sighting',
            old_name='time_of_day',
            new_name='tod',
        ),
    ]
