# Generated by Django 4.1.4 on 2022-12-20 19:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_rename_time_of_day_sighting_tod'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=50)),
                ('tracking', models.CharField(choices=[('L', 'Location'), ('F', 'Flight Patterns'), ('N', 'Nesting Habits')], default='L', max_length=1)),
            ],
        ),
        migrations.AlterModelOptions(
            name='sighting',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='sighting',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='sighting date'),
        ),
        migrations.AddField(
            model_name='finch',
            name='tags',
            field=models.ManyToManyField(to='main_app.tag'),
        ),
    ]
